version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
  app:
    build: .
    command: bundle exec foreman start -f Procfile.dev
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - mysql
